package com.ucoa.app

import android.content.Context
import android.os.Build
import org.json.JSONArray
import org.json.JSONObject
import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.HttpURLConnection
import java.net.URL
import java.util.UUID
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/** Thin mobile transport. Provider/model secrets stay in the cloud. */
class AgentBrainClient(private val context: Context) {
    data class Response(val ok: Boolean, val body: JSONObject?, val error: String? = null)
    private val executor: ExecutorService = Executors.newSingleThreadExecutor()
    private val prefs get() = context.getSharedPreferences("ucoa_brain", Context.MODE_PRIVATE)
    private val defaultEndpoint = "https://ucoa-agent-brain-69bo.onrender.com"
    private val legacyEndpoint = "https://ucoa-agent-brain.onrender.com"
    private val appVersion = "1.0.3"
    fun endpoint(): String {
        val saved = prefs.getString("endpoint", null)?.trim().orEmpty().trimEnd('/')
        if (saved.isBlank() || saved == legacyEndpoint) {
            if (saved == legacyEndpoint) prefs.edit().putString("endpoint", defaultEndpoint).apply()
            return defaultEndpoint
        }
        return saved
    }
    fun token(): String = prefs.getString("token", "")?.trim().orEmpty()
    fun configured(): Boolean = endpoint().isNotBlank()
    fun sessionId(): String { val current = prefs.getString("session_id", null); if (!current.isNullOrBlank()) return current; val created = UUID.randomUUID().toString().replace("-", ""); prefs.edit().putString("session_id", created).apply(); return created }
    private fun installId(): String { val current = prefs.getString("install_id", null); if (!current.isNullOrBlank()) return current; val created = UUID.randomUUID().toString().replace("-", ""); prefs.edit().putString("install_id", created).apply(); return created }
    fun resetSession() { prefs.edit().remove("session_id").remove("token").apply() }
    fun saveConfig(endpoint: String, token: String) { prefs.edit().putString("endpoint", endpoint.trim().trimEnd('/')).putString("token", token.trim()).apply() }
    fun bootstrap(callback: ((Response) -> Unit)? = null) = executor.execute { try { val body = ensureClientSession(); refreshRemoteConfig(); callback?.invoke(Response(true, body)) } catch (e: Exception) { callback?.invoke(Response(false, null, e.message ?: e.javaClass.simpleName)) } }
    fun health(callback: (Boolean, String) -> Unit) = readiness { transportOk, ready, detail -> callback(transportOk && ready, detail) }
    fun readiness(callback: (Boolean, Boolean, String) -> Unit) { val base = endpoint(); if (base.isBlank()) { callback(false, false, "عنوان العقل غير مُعد"); return }; executor.execute { try { val body = requestJson("GET", base + "/health", null, 15000); val ready = body.optBoolean("brain_configured", false); val vision = body.optString("vision_model", "غير متاح"); val reasoning = body.optString("reasoning_model", body.optString("model", "primary")); val provider = body.optString("reasoning_provider", "provider-router"); callback(true, ready, if (ready) "العقل جاهز: $provider/$reasoning | الرؤية: $vision" else "الخادم متصل لكن النموذج غير مهيأ") } catch (e: Exception) { callback(false, false, e.message ?: e.javaClass.simpleName) } } }
    fun fetchRemoteConfig(callback: (Response) -> Unit) = executor.execute { try { callback(Response(true, refreshRemoteConfig())) } catch (e: Exception) { callback(Response(false, null, e.message ?: e.javaClass.simpleName)) } }
    fun visionProbe(callback: (Response) -> Unit) = executor.execute { try { ensureClientSession(); callback(Response(true, requestJson("GET", endpoint() + "/v1/providers/probe-vision", null, 95000))) } catch (e: Exception) { callback(Response(false, null, e.message ?: e.javaClass.simpleName)) } }
    fun telemetry(kind: String, payload: JSONObject = JSONObject(), taskId: String? = null) = executor.execute { try { ensureClientSession(); requestJson("POST", endpoint() + "/v1/client/events", JSONObject().apply { put("install_id", installId()); put("session_id", sessionId()); if (!taskId.isNullOrBlank()) put("task_id", taskId); put("kind", kind); put("payload", payload); put("app_version", appVersion) }, 15000) } catch (_: Exception) { } }
    fun reportOutcome(outcome: String, metrics: JSONObject = JSONObject(), taskId: String? = null) = executor.execute { try { ensureClientSession(); requestJson("POST", endpoint() + "/v1/client/report", JSONObject().apply { put("install_id", installId()); put("session_id", sessionId()); if (!taskId.isNullOrBlank()) put("task_id", taskId); put("outcome", outcome); put("metrics", metrics) }, 15000) } catch (_: Exception) { } }
    fun queueTask(task: String, attachments: List<String> = emptyList(), metadata: JSONObject = JSONObject(), callback: (Response) -> Unit) = executor.execute { try { ensureClientSession(); val body = requestJson("POST", endpoint() + "/v1/client/commands", JSONObject().apply { put("install_id", installId()); put("kind", "task"); put("task", task); put("attachments", JSONArray(attachments.take(20))); put("metadata", metadata) }, 15000); callback(Response(true, body)) } catch (e: Exception) { callback(Response(false, null, e.message ?: e.javaClass.simpleName)) } }
    fun plan(task: String, attachments: List<String>, callback: (Response) -> Unit) { val payload = JSONObject().apply { put("task", task); put("attachments", JSONArray(attachments)); put("session_id", sessionId()); put("device", JSONObject().apply { put("manufacturer", Build.MANUFACTURER); put("model", Build.MODEL); put("android", Build.VERSION.SDK_INT); put("app_version", appVersion) }) }; submitJob("/v1/agent/plan", payload, "plan", callback, 180000) }
    fun step(task: String, step: Int, history: JSONArray, uiTree: String, screenshotBase64: String?, installedApps: List<String>, attachments: List<String>, approvedRisks: Boolean = false, callback: (Response) -> Unit) { val payload = JSONObject().apply { put("task", task); put("step", step); put("max_steps", remoteInt("max_steps", 60)); put("history", history); put("ui_tree", uiTree); put("session_id", sessionId()); put("approved_risks", approvedRisks); if (!screenshotBase64.isNullOrBlank()) put("screenshot_base64", screenshotBase64); put("installed_apps", JSONArray(installedApps.take(250))); put("attachments", JSONArray(attachments.take(20))); put("capabilities", JSONArray(listOf("open_url", "open_app_by_name", "click_any_text", "type_into_any", "share_attachment", "tap", "long_press", "swipe", "back", "home", "wait", "observe", "done"))); put("foreground_package", UcoaAccessibilityService.instance?.foregroundPackageName() ?: ""); val dm = context.resources.displayMetrics; put("screen_width", dm.widthPixels); put("screen_height", dm.heightPixels) }; submitJob("/v1/agent/step", payload, "step", callback, 75000) }
    fun persistExecutionState(task: String, step: Int, history: JSONArray, status: String, callback: ((Response) -> Unit)? = null) { val payload = JSONObject().apply { put("session_id", sessionId()); put("state", JSONObject().apply { put("task", task); put("step", step); put("status", status); put("history", history) }) }; executor.execute { try { ensureClientSession(); callback?.invoke(Response(true, requestJson("POST", endpoint() + "/v1/agent/state", payload, 15000))) } catch (e: Exception) { callback?.invoke(Response(false, null, e.message ?: e.javaClass.simpleName)) } } }
    fun verifyResult(task: String, action: JSONObject, beforeUi: String, afterUi: String, beforeScreenshot: String?, afterScreenshot: String?, callback: (Response) -> Unit) { val payload = JSONObject().apply { put("task", task); put("action", action); put("before_ui_tree", beforeUi); put("after_ui_tree", afterUi); put("session_id", sessionId()); put("foreground_package", UcoaAccessibilityService.instance?.foregroundPackageName() ?: ""); if (!beforeScreenshot.isNullOrBlank()) put("before_screenshot_base64", beforeScreenshot); if (!afterScreenshot.isNullOrBlank()) put("after_screenshot_base64", afterScreenshot) }; executor.execute { try { ensureClientSession(); callback(Response(true, requestJson("POST", endpoint() + "/v1/agent/verify-result", payload, 30000))) } catch (e: Exception) { callback(Response(false, null, e.message ?: e.javaClass.simpleName)) } } }
    private fun submitJob(path: String, payload: JSONObject, kind: String, callback: (Response) -> Unit, requestTimeoutMs: Int) = executor.execute { try { ensureClientSession(); refreshRemoteConfig(); val submitted = requestJson("POST", endpoint() + path, payload, requestTimeoutMs); val immediate = submitted.optJSONObject("result"); if (submitted.optString("status") == "completed" && immediate != null) { callback(Response(true, immediate)); return@execute }; val jobId = submitted.optString("job_id").takeIf { it.isNotBlank() } ?: throw IllegalStateException("Brain did not return a result or job_id"); pollJob(endpoint(), jobId, callback, 0) } catch (e: Exception) { callback(Response(false, null, e.message ?: e.javaClass.simpleName)) } }
    private fun pollJob(base: String, jobId: String, callback: (Response) -> Unit, attempt: Int) { val maxPolls = remoteInt("max_poll_attempts", 240); val pollMs = remoteInt("poll_interval_ms", 1000); if (attempt >= maxPolls) { callback(Response(false, null, "انتهت مهلة انتظار عقل AI")); return }; try { val job = requestJson("GET", base + "/v1/agent/jobs/$jobId", null, 15000); when (job.optString("status")) { "completed" -> { val result = job.optJSONObject("result"); callback(if (result != null) Response(true, result) else Response(false, null, "العقل أنهى المهمة بلا نتيجة")) }; "failed" -> callback(Response(false, null, job.optString("error", "فشل تشغيل عقل AI"))); else -> { Thread.sleep(pollMs.toLong()); pollJob(base, jobId, callback, attempt + 1) } } } catch (e: Exception) { callback(Response(false, null, e.message ?: e.javaClass.simpleName)) } }
    private fun ensureClientSession(): JSONObject { if (token().isNotBlank()) return JSONObject().put("reused", true); val payload = JSONObject().apply { put("install_id", installId()); put("app_version", appVersion); put("platform", "android"); put("device", JSONObject().apply { put("manufacturer", Build.MANUFACTURER); put("model", Build.MODEL); put("android", Build.VERSION.SDK_INT) }) }; val body = requestJson("POST", endpoint() + "/v1/client/session", payload, 15000); val sessionToken = body.optString("session_token"); if (sessionToken.isBlank()) throw IllegalStateException("Cloud did not issue a client session"); prefs.edit().putString("token", sessionToken).apply(); return body }
    private fun refreshRemoteConfig(): JSONObject { val body = requestJson("GET", endpoint() + "/v1/client/config?platform=android&app_version=$appVersion", null, 15000); prefs.edit().putString("remote_config", body.toString()).putLong("remote_config_at", System.currentTimeMillis()).apply(); return body }
    private fun remoteInt(key: String, defaultValue: Int): Int = try { prefs.getString("remote_config", null)?.let { JSONObject(it).optInt(key, defaultValue) } ?: defaultValue } catch (_: Exception) { defaultValue }
    private fun requestJson(method: String, url: String, payload: JSONObject?, timeout: Int): JSONObject { var attempts = 0; while (true) { attempts++; var conn: HttpURLConnection? = null; try { conn = (URL(url).openConnection() as HttpURLConnection).apply { requestMethod = method; connectTimeout = timeout; readTimeout = timeout; doInput = true; if (payload != null) { doOutput = true; setRequestProperty("Content-Type", "application/json") }; token().takeIf { it.isNotBlank() }?.let { setRequestProperty("Authorization", "Bearer $it") } }; if (payload != null) conn.outputStream.use { it.write(payload.toString().toByteArray(Charsets.UTF_8)) }; val code = conn.responseCode; val stream = if (code in 200..299) conn.inputStream else conn.errorStream; val text = BufferedReader(InputStreamReader(stream, Charsets.UTF_8)).use { it.readText() }; if (code !in 200..299) throw IllegalStateException("HTTP $code: ${text.take(1200)}"); return JSONObject(text) } catch (e: java.net.UnknownHostException) { if (attempts >= 4) throw e; Thread.sleep(1500L * attempts) } catch (e: java.io.IOException) { if (attempts >= 4) throw e; Thread.sleep(1000L * attempts) } finally { conn?.disconnect() } } }
}
