package com.ucoa.app

import android.app.Activity
import android.graphics.BitmapFactory
import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.widget.*
import android.graphics.Color
import android.util.Base64

class ModernMainActivity : Activity() {
    private lateinit var chat:LinearLayout; private lateinit var status:TextView; private lateinit var input:EditText; private lateinit var brain:AgentBrainClient
    private var loop:UniversalAgentLoop?=null; private var waitingRequest:HumanIntervention.Request?=null
    private val bg=Color.rgb(14,16,23); private val card=Color.rgb(23,26,36); private val card2=Color.rgb(31,34,47); private val white=Color.rgb(245,246,250); private val muted=Color.rgb(158,163,178); private val purple=Color.rgb(124,92,255); private val green=Color.rgb(63,198,132); private val red=Color.rgb(232,70,84)
    override fun onCreate(state:Bundle?){super.onCreate(state);brain=AgentBrainClient(this);window.decorView.layoutDirection=View.LAYOUT_DIRECTION_RTL;setContentView(build());refreshStatus()}
    private fun build():View{val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(bg);setPadding(18,18,18,10)};val head=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL};head.addView(tv("الذكاء العملي الكامل",24,white,true));status=tv("جاري فحص الاتصال…",12,muted,false);head.addView(status);root.addView(head);val scroll=ScrollView(this).apply{layoutParams=LinearLayout.LayoutParams(-1,0,1f)};chat=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(0,18,0,18)};scroll.addView(chat);root.addView(scroll);addCard("ابدأ مهمة جديدة","اكتب ما تريد، وسأحل المشكلات تلقائيًا قبل أن أطلب منك أي تدخل.",purple);val composer=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val attach=Button(this).apply{text="＋";setOnClickListener{toast("اختر الوسائط من منتقي الملفات")}};input=EditText(this).apply{hint="اكتب ما تريد تنفيذه…";setTextColor(white);setHintTextColor(muted);setBackgroundColor(card2);setPadding(14,10,14,10);layoutParams=LinearLayout.LayoutParams(0,56,1f)};val send=Button(this).apply{text="إرسال";setOnClickListener{startTask()}};composer.addView(attach,LinearLayout.LayoutParams(52,56));composer.addView(input);composer.addView(send,LinearLayout.LayoutParams(76,56));root.addView(composer);return root}
    private fun refreshStatus(){brain.readiness{transport,ready,detail->runOnUiThread{status.text=if(transport&&ready)"● العقل متصل — التنفيذ والمراقبة جاهزان" else "○ ${detail.take(120)}"}}}
    private fun startTask(){val task=input.text.toString().trim();if(task.isEmpty())return;input.setText("");addUser(task);addAssistant("أفهم المهمة وأبني خطة قابلة للاستئناف…");loop=UniversalAgentLoop(brain);loop!!.start(task,object:UniversalAgentLoop.Listener{override fun onEvent(text:String){runOnUiThread{status.text=text.take(160);addAssistant(text.take(700))}};override fun onHumanIntervention(request:HumanIntervention.Request){runOnUiThread{waitingRequest=request;showHuman(request)}};override fun onConfirmationRequired(reasons:String){runOnUiThread{showDecision("التأكيد مطلوب",reasons,listOf("مراجعة العملية","إلغاء"))}};override fun onFinished(success:Boolean){runOnUiThread{if(success)showResult() else if(waitingRequest==null)addAssistant("توقفت المهمة فقط بعد استنفاد محاولات الحل الآلي الآمنة.")}}})}
    private fun showHuman(r:HumanIntervention.Request){val actions=when(r.kind){"signup"->listOf("نفذ التسجيل بنفسي","تم التسجيل — متابعة","إلغاء");"verification"->listOf("أدخل الرمز بنفسي","تم التحقق — متابعة","إلغاء");"subscription","credits"->listOf("متابعة الاشتراك","استخدام خدمة بديلة","رفض");else->listOf(r.actionLabel,"إلغاء")};showDecision(r.title,r.message,actions){choice->when(choice){0->toast("نفذ الإجراء في الخدمة ثم عد واضغط متابعة");1->{waitingRequest=null;loop?.resume()};2->loop?.stop()}}}
    private fun showDecision(title:String,message:String,actions:List<String>,done:((Int)->Unit)?=null){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,12,24,8);setBackgroundColor(card)};box.addView(tv(title,20,white,true));box.addView(tv(message,14,muted,false));actions.forEachIndexed{i,a->box.addView(Button(this).apply{text=a;setOnClickListener{done?.invoke(i)}})};android.app.AlertDialog.Builder(this).setView(box).show()}
    private fun showResult(){addAssistant("اكتملت المهمة بعد التحقق. النتيجة محفوظة للمراجعة والتعديل الجزئي.");val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16,16,16,16);setBackgroundColor(card)};box.addView(tv("المعاينة النهائية",19,white,true));val image=ImageView(this).apply{adjustViewBounds=true;setBackgroundColor(Color.BLACK)};box.addView(image,LinearLayout.LayoutParams(-1,280));val row=LinearLayout(this);row.addView(Button(this).apply{text="موافقة";setOnClickListener{addAssistant("تم اعتماد النتيجة.")}},LinearLayout.LayoutParams(0,56,1f));row.addView(Button(this).apply{text="تعديل";setOnClickListener{showRevision()}},LinearLayout.LayoutParams(0,56,1f));box.addView(row);chat.addView(box);UcoaAccessibilityService.instance?.captureScreenshotBase64{b64->runOnUiThread{if(!b64.isNullOrBlank()){val bytes=Base64.decode(b64,Base64.DEFAULT);image.setImageBitmap(BitmapFactory.decodeByteArray(bytes,0,bytes.size))}}}}
    private fun showRevision(){val e=EditText(this).apply{hint="ما التعديل المطلوب؟";setTextColor(white);setHintTextColor(muted);minLines=4};android.app.AlertDialog.Builder(this).setTitle("تعديل النتيجة").setMessage("سيتم استهداف الجزء المتأثر وإعادة استخدام النتيجة والموارد المحفوظة.").setView(e).setNegativeButton("إلغاء",null).setPositiveButton("تنفيذ التعديل"){_,_->val q=e.text.toString().trim();if(q.isNotEmpty()){addAssistant("طلب التعديل: $q");addAssistant("سيُربط التعديل بالخطوة المتأثرة بدل إعادة المهمة كاملة.")}}.show()}
    private fun addUser(s:String)=addBubble("أنت\n$s",true);private fun addAssistant(s:String)=addBubble("الوكيل\n$s",false);private fun addCard(t:String,b:String,c:Int){val l=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(18,16,18,16);setBackgroundColor(card)};l.addView(tv(t,17,white,true));l.addView(tv(b,13,muted,false));chat.addView(l,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,0,0,12)})};private fun addBubble(s:String,user:Boolean){val l=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16,14,16,14);setBackgroundColor(if(user)Color.rgb(43,38,72) else card)};l.addView(tv(s,14,white,user));chat.addView(l,LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,0,0,10)})};private fun tv(s:String,size:Float,color:Int,bold:Boolean)=TextView(this).apply{text=s;textSize=size;setTextColor(color);setTypeface(null,if(bold)android.graphics.Typeface.BOLD else android.graphics.Typeface.NORMAL);setPadding(2,4,2,4)};private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
}
